export default {
  LOGIN: '[auth] LOGIN',
  REGISTER: '[auth] REGISTER',
  UPDATE_PASSWORD: '[auth] UPDATE_PASSWORD',
  RESET_PASSWORD: '[auth] RESET_PASSWORD',
  LOGOUT: '[auth] LOGOUT',
  CHECK_PLAN: '[shop] CHECK_PLAN',
  FREEZE_PLAN: '[shop] FREEZE_PLAN',
  TOGGLE_RESERVATION: '[trainings] TOGGLE_RESERVATION',
  TOGGLE_NOTIFICATIONS: '[trainings] TOGGLE_NOTIFICATIONS',
  CHECK_IN: '[trainings] CHECK_IN',
};
