export default {
  IS_LOGGED_IN: '[auth] IS_LOGGED_IN',
  USER_DATA: '[event] USER_DATA',
  STATS_DATA: '[stats] STATS_DATA',
  STATS_POINTS: '[stats] STATS_POINTS',
  STATS_POINTS_SUM: '[stats] STATS_POINTS_SUM',
  STAT_ENTRIES_PER_MONTH: '[stats] STAT_ENTRIES_PER_MONTH',
  STAT_ENTRIES_PER_WEEK: '[stats] STAT_ENTRIES_PER_WEEK',
  TRAININGS_CLASSES: '[trainings] TRAININGS_CLASSES',
  TRAININGS_PTS: '[trainings] TRAININGS_PTS',
  MEMBERSHIPS: '[shop] MEMBERSHIPS',
  PACKAGES: '[shop] PACKAGES',
};
