export default {
  SET_USER_DATA: '[auth] SET_USERDATA',
  CLEAR_USER_DATA: '[auth] CLEAR_USERDATA',
  SET_STATS_DATA: '[stats] SET_STATS_DATA',
  SET_TRAININGS_CLASSES: '[trainings] SET_TRAININGS_CLASSES',
  SET_TRAININGS_PTS: '[trainings] SET_TRAININGS_PTS',
  SET_MY_TRAININGS: '[trainings] SET_MY_TRAININGS',
  SET_TRAINERS: '[trainers] SET_TRAINERS',
  SET_MEMBERSHIPS: '[shop] SET_MEMBERSHIPS',
  SET_PACKAGES: '[shop] SET_PACKAGES',
  SELECT_PLAN_FOR_BUYING: '[shop] SELECT_PLAN_FOR_BUYING',
  SET_START_DATE_FOR_PLAN: '[shop] SET_START_DATE_FOR_PLAN',
};
