export default {
  SET_USER_DATA: '[auth] SET_USERDATA',
  CLEAR_USER_DATA: '[auth] CLEAR_USERDATA',
  SET_STATS_DATA: '[stats] SET_STATS_DATA',
  SET_TRAININGS_CLASSES: '[trainings] SET_TRAININGS_CLASSES',
  SET_TRAININGS_PTS: '[trainings] SET_TRAININGS_PTS',
  SET_TRAINERS: '[trainers] SET_TRAINERS',
  SET_MEMBERSHIPS: '[shop] SET_MEMBERSHIPS',
  SET_PACKAGES: '[shop] SET_PACKAGES',
};
